app/urls.py
from django.urls import path
from .views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleDeleteView, ArticleUpdateView

urlpatterns = [
    path("", ArticleListView.as_view(), name="home"),
    path("create/", ArticleCreateView.as_view(), name="article_create"),
    path("<int:pk>/detail/", ArticleDetailView.as_view(), name="article_detail"),
    path("<int:pk>/update/", ArticleUpdateView.as_view(), name="article_update"),
    path("<int:pk>/delete/", ArticleDeleteView.as_view(), name="article_delete"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("articles/", include("app.urls")),
    path('accounts/', include('allauth.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", RedirectView.as_view(pattern_name="home")),
    path("__reload__/", include("django_browser_reload.urls")),

]

app/models.py
import re

from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

from app.managers import UserProfileManager

# Create your models here.

ARTICLE_STATUS = (
        ("draft", "Draft"),
        ("in progress", "In progress"), 
        ("published", "Published"),
    )

class UserProfile(AbstractUser):
    email = models.EmailField(max_length=255, unique=True)

    objects = UserProfileManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    @property
    def article_count(self):
        return self.articles.count()
    
    @property
    def written_words(self):
        return self.articles.aggregate(models.Sum("word_count"))["word_count__sum"] or 0

class Article(models.Model):                                                               
    title = models.CharField(max_length=100)
    content = models.TextField(blank=True, default="")
    word_count = models.IntegerField(blank=True, default="")
    twitter_post = models.TextField(blank=True, default="")
    status = models.CharField(max_length=20, 
                                choices=ARTICLE_STATUS,
                                default="draft"
                            )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="articles")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        text = re.sub(r"<[^>]*>","", self.content).replace("&nbsp;", " ")
        self.word_count = len(re.findall(r"\b\w+\b", text))
        super().save(*args, **kwargs)

app/views.py
from typing import Any
import time
from django.contrib import messages
from django.http import HttpRequest, HttpResponse
from .models import Article
from django.db.models.query import QuerySet
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy 
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
# Create your views here.


class ArticleListView(ListView):
    model = Article
    template_name = "app/home.html"
    paginate_by = 5

    def get_queryset(self) -> QuerySet[Any]:
        time.sleep(2)
        search = self.request.GET.get("search")
        queryset = super().get_queryset().filter(creator=self.request.user.id)
        if search:
            queryset = queryset.filter(title__search=search)
        return queryset.order_by("-created_at")


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    fields = ["title", "status", "content", "twitter_post"]
    success_url = reverse_lazy("home")
    template_name = "app/article_create.html"

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)


class ArticleDetailView(LoginRequiredMixin, DetailView):
    model = Article
    template_name = "app/article_detail.html"


class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Article
    fields = ["title", "status", "content", "twitter_post"]
    template_name = "app/article_update.html"
    success_url = reverse_lazy("home")

    def test_func(self):
        return self.request.user == self.get_object().creator


class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Article
    template_name = "app/article_delete.html"
    success_url = reverse_lazy("home")
   

    def test_func(self):
        return self.request.user == self.get_object().creator
    
    def post(self, request:HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        messages.success(request, "Article deleted successfully.", extra_tags="destructive") 
        return super().post(request, *args, **kwargs)

templates/app/article_create.html
{% extends 'app/layouts/base_form.html' %}

{% block head_title %}
- Create article
{% endblock head_title %}

{% block buttons %}
<div class="flex justify-end gap-4">
    <button type="submit" class="button primary">Create</button>
</div>
{% endblock buttons %}

templates/app/article_delete.html
{% extends 'base.html' %}

{% block head_title %}
- Delete article
{% endblock head_title %}

{% block base_content %}
<main class="max-w-2xl mx-auto flex flex-col items-center mt-10">
    <h1 class="subtitle mb-2">Delete Article</h1>
    <p class="text-lg mb-6">Are you sure you want to delete "{{article.title}}"?</p>

    <form method="post" class="flex items-center gap-4" action="{% url 'article_delete' article.pk %}">
        {% csrf_token %}
        <button type="submit" class="button danger">Yes, delete it</button>
        <a href="{% url 'article_update' article.pk %}" class="button secondary">{% include "svgs/arrow-left.svg" with class="inline-block w-6 h-6 mr-2 mt-[-2px]" %}No, take me back</a>
    </form>
</main>
{% endblock base_content %}

templates/app/article_detail.html
{% extends 'base.html' %}

{% block head_title %}
- article details
{% endblock head_title %}

{% block base_content %}
    <h3>{{ article.title }}</h3>
    <div>
        <p>{{ article.created_at }}</p>
        <p>{{ article.updated_at }}</p>
        <p>{{ article.content }}</p>
    </div>
{% endblock base_content %}
    

templates/app/article_update.html
{% extends 'app/layouts/base_form.html' %}

{% block head_title %}
- Update article
{% endblock head_title %}

{% block article_stats %}
    <p>{{ article.word_count }} word{{ article.word_count | pluralize }}.</p>
    <p>Last edited on <span class="font-bold">{{ article.updated_at | date:"jS F Y" }}</span></p>
{% endblock article_stats %}   

{% block buttons %}
<div class="flex justify-end gap-4">
    <a hx-get="{% url 'article_delete' article.pk %}" class="button danger" hx-target="#dialog" hx-select="main">Delete Article</a>
    <button type="submit" class="button primary">Save</button>
</div>
{% endblock buttons %}

{% block extra_body %}
<div id="modal" class="relative z-10 hidden">
    <div class="bg-black/15 fixed inset-0 "></div>
    <div class="fixed inset-0 z-10  w-screen p-4">
        <div id="dialog" class="max-w-lg mx-auto bg-white p-16 rounded-md shadow-lg"></div>
    </div>
</div>
{% endblock extra_body %}

{% block page_js %}
{{ block.super }}

<script type="application/javascript">
    const modal = document.getElementById("modal");

    htmx.on("htmx:afterSwap", function(e) {
        if (e.detail.target.id == "dialog") {
            modal.classList.toggle("hidden");
        }
    })
</script>
{% endblock page_js %}

templates/app/home.html
{% extends 'base.html' %}
{% load humanize %}

{% block head_title %}
- Your articles
{% endblock %}


{% block base_content %}

<main class="max-w-7xl mx-auto mt-10 p-2 md:p-4 lg:p-10">
    <h1 class="title mb-4">Welcome</h1>

    <p class="text-x1 mb-4"> You have created {{ user.article_count | intcomma }} 
        article{{ user.article_count | pluralize }} and written {{ user.written_words | intcomma }} 
        word{{ user.written_words | pluralize}}.
    </p>

    <a class="button primary inline-block mb-6 w-full sm:w-auto text-center" href="{% url 'article_create' %}">New Article </a>

    <h2 class="subtitle mb-6">Your latest articles</h2>

    <form method="GET" class="flex flex-col sm:flex-row gap-3 form-field">
        <input class="text-black shadow-sm focus:ring-emerald-500 focus:border-emerald-500 sm:text-sm border-gray-300 rounded-md" 
        type="search" name="search" placeholder="Search articles" value="{{request.GET.search}}" 
        hx-get="{{ request.path }}"
        hx-trigger="input changed delay:500ms, search" 
        hx-target="#article-results"
        hx-select="#article-results"
        hx-indicator="svg.loading"
        hx-disabled-elt="next button"
        hx-push-url="true">
        
        <button class="flex gap-1 button secondary items-center justify-center [&>.loading.htmx-request.hidden]:!inline-block [&>.loading.htmx-request]:hidden disabled:cursor-not-allowed disabled:opacity-50" type="submit">
            {% include "svgs/magnifier.svg" with class="loading w-6 h-6 mr-2" %}
            {% include "svgs/loading.svg" with class="loading w-6 h-6 mr-2 hidden motion-safe:animate-spin" %}
            Search
        </button>
        <a href="{{ request.path }}" class="button secondary text-center">Clear search</a>
    </form>

<div id="article-results">
    {% if article_list %}
    <ul preload="mouseover">
        {% for article in article_list %}
            <li>
                <a class="text-2xl flex items-center" href="{% url 'article_update' article.pk %}">{{ article.title }} 
                    <span class="ml-2 px-4 py-0.5 text-xs rounded-sm uppercase article-status-{{article.status}}">{{ article.status }}</span>
                </a>
                <p class="text">{{ article.word_count }} word{{ article.word_count | pluralize }}</p> 
            </li>
        {% endfor %}
    </ul>  
        {% if is_paginated %}
        <div class="flex flex-row items-center justify-center text-xl mt-6">
            {% if page_obj.has_previous %}
                <a class="mx-2" href="?page={{ page_obj.previous_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">
                    {% include "svgs/chevron.svg" with class="h-7 w-7 rotate-180 border-black rounded-md p-1"%}
                </a>
            {% endif %}
                <span>Page {{ page_obj.number }} of {{ paginator.num_pages }}</span>
            {% if page_obj.has_next %}
                <a class="mx-2" href="?page={{ page_obj.previous_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">
                    {% include "svgs/chevron.svg" with class="h-7 w-7 border-black rounded-md p-1"%}
                </a>

            {% endif %}
        </div>
        {% endif %}
    {% else %}
    <p>There are no articles yet.</p>
    {% endif %}
</div>
</main>
{% endblock base_content %}

templates/app/layouts/base_form.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block base_content %}
<main class="max-w-7xl mx-auto mt-10">
   <form method="post" x-data="{articleStatus: ''}">
      {% csrf_token %}
      <div class="mb-4">
         {% render_field form.title class="text-4xl w-full rounded-md border-2 border-gray-200 focus:ring-1 focus:ring-emerald-500 focus:border-emerald-500" placeholder="Write a title for your article" %}
      </div>
      <div class="flex gap-10 mb-10 items-center">
         {% render_field form.status class="text-xs border-none rounded-sm uppercase article-status-draft"x-bind::class="`article-status-{articleStatus}`" x-model.fill="articleStatus" %}

         {% block article_stats %}

         {% endblock article_stats %}
      </div>

      <div class="mb-10">
         {% render_field form.content rows=20 %}
      </div>

      <div class="mb-10">
         <p class="text-xl font-semibold mb-2">{{ form.twitter_post.label }}</p>
         {% render_field form.twitter_post rows=10 class="w-full" %}
      </div>


      {% block buttons %}

      {% endblock buttons %}
   </form>
</main>
{% endblock base_content %}

{% block page_js %}
<script>
   const contentMarkdown = new EasyMDE({
   element: document.getElementById('id_content'),
   spellChecker: false,
   status: false,
   toolbar: false,
   forceSync: true
   });
</script>
{% endblock page_js %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Connecto {% block head_title %}{% endblock head_title %}</title>
    <link rel="stylesheet" href="{% static 'output.css'%}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.css">
    <script src="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.js"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.14.3/dist/cdn.min.js"></script>
    <script src="https://unpkg.com/htmx.org@2.0.4" integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+" crossorigin="anonymous"></script>
    {% block extra_head %}
    {% endblock extra_head %}
    

</head>

<body>
    {% block body%}
    {% url 'article_create' as create_new_url %}
    {% url 'home' as your_articles_url %}
    {% url 'account_email' as change_email_url %}
    <nav class="px-10 py-4 border-b border-gray-300 shadow-md">
        <div class="flex justify-end items-center gap-6 max-w-7xl mx-auto">
            
                {% if user.is_authenticated %}
                <a
                class="button primary" 
                href="{% if request.path != create_new_url %} {{ create_new_url }} {% else %} # {% endif %}">
                Create New
                </a>
                <a
                class="hover:shadow-underline hover:shadow-gray-300 {% if request.path == your_articles_url %} font-semibold {% endif %}" href="{{ your_articles_url }}">
                Articles
                </a>
                <a 
                class="hover:shadow-underline hover:shadow-gray-300 {% if request.path == change_email_url %} font-semibold {% endif %}" href="{{ change_email_url }}">
                Change email
                </a>
                <form method="POST" action="{% url 'account_logout' %}">
                    {% csrf_token %}
                    <button class="" type="submit">Logout</button>
                </form>
                {% else %}
                <a class="button secondary text-sm" href="{% url 'account_login' %}">Login</a>
                <a class="button primary text-sm" href="{% url 'account_signup' %}">Sign up</a>
                {% endif %}
            
        </div>
    </nav>
    <div class="p-2 md:p-4 lg:p-6">
        <div class="flex justify-center mt-2 text-gray-500 font-bold">
        {% if messages %}
        <ul>
            {% for message in messages%}
                <li class="border p-2 border-gray-400 bg-gray-200 rounded-md {{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        </div>

        {% block base_content %}

        {% endblock base_content %}
    </div>
    {% endblock body %}
    {% block extra_body %}
    {% endblock extra_body %}

    {% block page_js %}
    {% endblock page_js%}

</body>

</html>